version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: perspective-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=perspective
      - ssl=on
    ports:
      - '5435:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
